---
# tasks file for Dell-Networking.dellos-lldp

 - name: "Generating LLDP configuration for dellos9"
   template:
      src: dellos9_lldp.j2
      dest: "{{ build_dir }}/lldp9_{{hostname}}.conf.part"
   when: (ansible_network_os == "dellos9" or ansible_net_os_name == "dellos9") and ((dellos_cfg_generate | default('False')) | bool) 
#   notify: save config os9
   register: generate_output

 - name: "Provisioning LLDP configuration for dellos9"
   dellos9_config:
      src: dellos9_lldp.j2
   when: (ansible_network_os == "dellos9" or ansible_net_os_name == "dellos9")
#   notify: save config os9
   register: output

 - name: "Generating LLDP configuration for dellos10"
   template:
      src: dellos10_lldp.j2
      dest: "{{ build_dir }}/lldp10_{{hostname}}.conf.part"
   when: (ansible_network_os == "dellos10" or ansible_net_os_name == "dellos10") and ((dellos_cfg_generate | default('False')) | bool)
#   notify: save config os10
   register: generate_output

 - name: "Provisioning LLDP configuration for dellos10"
   dellos10_config:
      src: dellos10_lldp.j2
   when: (ansible_network_os == "dellos10" or ansible_net_os_name == "dellos10")
#   notify: save config os10
   register: output

